## Práctica 1. Consultas con MongoDB

En esta práctica se trabaja con la base de datos de ejemplo `sample_mflix` y la colección `movies`, utilizando MongoDB Shell, MongoDB Compass y `mongoexport`.

Se abordan:

- consultas básicas sobre documentos;
- operadores de comparación;
- consultas sobre campos anidados;
- consultas sobre arreglos;
- uso de `$exists`;
- combinación de condiciones;
- conteo de documentos con `countDocuments()`;
- uso de MongoDB Compass;
- construcción de una consulta propia;
- exportación de resultados en JSON o CSV.

<a class="btn btn-primary"
   href="practicas/01_mongodb_local.html">
   Abrir práctica
</a>

## Práctica 2. Modelado de relaciones con `sample_mflix`

Análisis de la estructura de la base `sample_mflix` mediante **MongoDB Compass** y **Data Modeling**, identificando relaciones entre colecciones, campos de referencia e información incrustada.

<a class="btn btn-primary"
   href="practicas/02_modelado_relaciones_mongodb.html">
   Abrir práctica
</a>

---

## Práctica 3. Manejo de datos clave–valor con Redis

Aplicación de los principales comandos y estructuras de Redis mediante el escenario de una tienda en línea. Se trabajará con productos, stock, sesiones, contadores, colas, usuarios únicos y rankings.

<a class="btn btn-primary"
   href="practicas/03_redis_clave_valor.html">
   Abrir práctica
</a>